### ISSUE TITLE
Globbing is incorrect for Windows style paths

### ISSUE THREAD

**Issue by alesvaupotic** [antfu/vite-plugin-restart#1]
On Win10, with project in 

`C:\Users\ales\code\_templates_\svelte-vite-windi` 

and ​config of 

`restart: ["windi.config.cjs"],`

restartGlobs is set to

`[​"C:\\Users\\ales\\code\\_templates_\\svelte-vite-windi/C:/Users/ales/code/_templates_/svelte-vite-windi/windi.config.cjs"]
`

and file change recognition is not working.

What works for me is replacing posix.resolve with 

`
restartGlobs = toArray(options.restart).map((i2) => i2.replace(/\\/g, "/"));
`

There probably is a more robust solution than that, I am just trying to pinpoint the culprits.

**Comment by antfu** [comment]
Would you mind sending a quick PR? Thanks!

**Comment by alesvaupotic** [comment]
Sure, let me sort out a working solution for both systems and get back here.

**Comment by alesvaupotic** [comment]
Just seen your response on the lock file, I see you did it yourself and merged already. Thanks, appreciate the quick turnaround.
