### ISSUE TITLE
Look for new file and file deletion

### ISSUE THREAD

**Issue by NicolaSpadari** [antfu/vite-plugin-restart#3]
I run this plugin in vite + vue 3, with [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages).
I need to watch for changes under the `src/pages` folder, when a file is created or deleted the server needs to restart, since the other plugins throws an error if i navigate to the page and the server wasn't restarted.

Can't seem to observe the files in a folder with this plugin.
No support or I just don't undestand how?

**Comment by antfu** [comment]
Yeah, we only listen to `change` at this moment https://github.com/antfu/vite-plugin-restart/blob/d8d5b9de7f2197ca1d8604597e380bd207203437/src/index.ts#L100

PR welcome, thanks!

**Comment by williamyorkl** [comment]
ohh~~ this is what I need also, and I am now working on it... but it seems that I have met a problem：
   how can I control the whole vite server to restart ? ( instead of just the vite websocket server, because I know there is a way to restart the vite websocket server, using `ViteDevServer.close()` or `ViteDevServer.listen()`, but if do so, only the websocket server will restart, not the whole vite server )
  the reason why I try to restart the whole vite server is  that I want to reload the Vite Plugins.... lol

**Comment by NicolaSpadari** [comment]
For some reason I'm not being able to filter files in a folder using glob patterns, so I ended up doing some "manual" controls just passing the name of the folder under `/src`
Anyway, this is my small custom plugin for restarting the server when a file under the `/pages` folder changes: [link](https://pastebin.com/XuRfABhD)

**Comment by williamyorkl** [comment]
> For some reason I'm not being able to filter files in a folder using glob patterns, so I ended up doing some "manual" controls just passing the name of the folder under `/src`
> Anyway, this is my small custom plugin for restarting the server when a file under the `/pages` folder changes: [link](https://pastebin.com/XuRfABhD)

bro, thanks for your plugin though, but as the code shows, you are using `server.ws.send({ type: "full-reload" })` , which it can only reload the pages instead of  reload the vite entity..... so I think this might not be a true reload ?

**Comment by NicolaSpadari** [comment]
I don't think so, since the plugin touches the `vite.config` file, which is the file that causes the instance to update.
When I create a page for example, this pops up in the terminal
![server-restart](https://user-images.githubusercontent.com/25949931/131975608-9826cc21-b03a-4f82-8fb3-15a58b219cb7.jpg)

**Comment by williamyorkl** [comment]
> I don't think so, since the plugin touches the `vite.config` file, which is the file that causes the instance to update.
> When I create a page for example, this pops up in the terminal
> ![server-restart](https://user-images.githubusercontent.com/25949931/131975608-9826cc21-b03a-4f82-8fb3-15a58b219cb7.jpg)

thanks a million bro, I just miss the `touch()`, and now works on my side !! thanks !

**Comment by raray** [comment]
Is there any chance of getting this into the plugin?
